version: '3.8'

services:
  floorplan_nest:
    build: ./backend
    container_name: floorplan_nest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - floorplan_db

  floorplan_db:
    image: postgres:13
    container_name: floorplan_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: floorplan_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
