version: '3.8'

services:
  floorplan_nest:
    build: ./backend
    container_name: floorplan_nest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - floorplan_db

  floorplan_db:
    image: mongo:4.4
    container_name: floorplan_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
