version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - floorplan_nest_prueba1:floorplan_nest_prueba1
      - floorplan_nest_prueba2:floorplan_nest_prueba2
      - floorplan_nest_prueba3:floorplan_nest_prueba3
    depends_on: 
      - floorplan_nest_prueba1 
      - floorplan_nest_prueba2 
      - floorplan_nest_prueba3

  floorplan_nest_prueba1:
    image: floorplanms-floorplan_nest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    hostname: "floorplan_nest_prueba1"
    expose:
      - "3000"
    ports:
      - "3001:3000"
    depends_on:
      - floorplan_db
    cpu_quota: 25000

  floorplan_nest_prueba2:
    image: floorplanms-floorplan_nest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    hostname: "floorplan_nest_prueba2"
    expose:
      - "3000"
    ports:
      - "3002:3000"
    depends_on:
      - floorplan_db
    cpu_quota: 25000


  floorplan_nest_prueba3:
    image: floorplanms-floorplan_nest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    hostname: "floorplan_nest_prueba3"
    expose:
      - "3000"
    ports:
      - "3003:3000"
    depends_on:
      - floorplan_db
    cpu_quota: 25000


  floorplan_db:
    image: mongo:4.4
    container_name: floorplan_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
volumes: 
  mongo_data: